In [1]:
%%time
%matplotlib inline
import importlib
import new_import  
importlib.reload(new_import)
from new_import import *

CPU times: user 13.5 s, sys: 3.89 s, total: 17.4 s
Wall time: 10.9 s


In [27]:
%%time
# Cấu hình Daskgateway
cluster, client = notebook_utils.initialize_dask(use_gateway=True, workers=(1,10))
# Khai báo 1 Datacube là dc
dc = datacube.Datacube()

client

An existing cluster was found. Connecting to: easihub.c4dbffb9cdd74f19847caf699e03780c
CPU times: user 30.8 ms, sys: 5.69 ms, total: 36.5 ms
Wall time: 152 ms


<Client: 'tls://10.0.61.109:8786' processes=1 threads=8, memory=28.00 GiB>

In [28]:
# cấu hình thời gian lấy ảnh và tọa độ
date_range = ('2024-05-01', '2024-5-31')
longtitude_range = (105.86575, 105.94120)
latitude_range = (9.65070, 9.69850)

coordinates = (longtitude_range, latitude_range)

In [29]:
# tải dữ liệu vh vv từ vệ tinh sentinel-1
dsvh, dsvv = load_data_sen1(dc, date_range, coordinates)

<xarray.Dataset>
Dimensions:      (time: 2, y: 532, x: 830)
Coordinates:
  * time         (time) datetime64[ns] 2024-05-10T22:46:16.500000 2024-05-22T...
  * y            (y) float64 1.072e+06 1.072e+06 ... 1.067e+06 1.067e+06
  * x            (x) float64 5.95e+05 5.95e+05 5.95e+05 ... 6.033e+05 6.033e+05
    spatial_ref  int32 32648
Data variables:
    vv           (time, y, x) float32 dask.array<chunksize=(1, 532, 830), meta=np.ndarray>
    vh           (time, y, x) float32 dask.array<chunksize=(1, 532, 830), meta=np.ndarray>
Attributes:
    crs:           EPSG:32648
    grid_mapping:  spatial_ref

In [30]:
average_vh = calculate_average(dsvh, time_pattern='1M')
progress(average_vh)

VBox()

In [31]:
average_vv = calculate_average(dsvv, time_pattern='1M')
progress(average_vv)

VBox()

In [32]:
%%time
average_vh.compute()
average_vv.compute()

CPU times: user 10.8 ms, sys: 687 µs, total: 11.5 ms
Wall time: 20.5 ms


<xarray.DataArray 'vv' (time: 1, y: 532, x: 830)>
array([[[0.15881254, 0.15881254, 0.19666761, ..., 0.09308143,
         0.09308143, 0.12172551],
        [0.18446743, 0.18446743, 0.22624001, ..., 0.11879794,
         0.11879794, 0.15596746],
        [0.18446743, 0.18446743, 0.22624001, ..., 0.11879794,
         0.11879794, 0.15596746],
        ...,
        [0.12267333, 0.13048397, 0.13048397, ..., 0.2505657 ,
         0.20839426, 0.20839426],
        [0.12267333, 0.13048397, 0.13048397, ..., 0.2505657 ,
         0.20839426, 0.20839426],
        [0.12267333, 0.13048397, 0.13048397, ..., 0.2505657 ,
         0.20839426, 0.20839426]]], dtype=float32)
Coordinates:
  * y            (y) float64 1.072e+06 1.072e+06 ... 1.067e+06 1.067e+06
  * x            (x) float64 5.95e+05 5.95e+05 5.95e+05 ... 6.033e+05 6.033e+05
    spatial_ref  int32 32648
  * time         (time) datetime64[ns] 2024-05-31
Attributes:
    units:         intensity
    nodata:        nan
    crs:           EPSG:32648
    grid_mapping:  spatial_ref

In [33]:
data_sen2 = load_data_sen2(dc, date_range, coordinates)
notebook_utils.heading(notebook_utils.xarray_object_size(data_sen2))
display(data_sen2)

No datasets require offset correction
The valid_data_mask and scale (no offset) have been applied to the reflectance bands


<xarray.Dataset>
Dimensions:      (time: 6, y: 532, x: 830)
Coordinates:
  * time         (time) datetime64[ns] 2024-05-04T03:35:29.391000 ... 2024-05...
  * y            (y) float64 1.072e+06 1.072e+06 ... 1.067e+06 1.067e+06
  * x            (x) float64 5.95e+05 5.95e+05 5.95e+05 ... 6.033e+05 6.033e+05
    spatial_ref  int32 32648
Data variables:
    red          (time, y, x) float32 dask.array<chunksize=(1, 532, 830), meta=np.ndarray>
    nir          (time, y, x) float32 dask.array<chunksize=(1, 532, 830), meta=np.ndarray>
    scl          (time, y, x) uint8 dask.array<chunksize=(1, 532, 830), meta=np.ndarray>
Attributes:
    crs:           EPSG:32648
    grid_mapping:  spatial_ref

In [34]:
%%time
# Tiến hành loại bỏ các vị trí bị mây ảnh hưởng
result = mask_cloud(data_sen2)
progress(result)

{'0': 'no data',
 '1': 'saturated or defective',
 '2': 'dark area pixels',
 '3': 'cloud shadows',
 '4': 'vegetation',
 '5': 'bare soils',
 '6': 'water',
 '7': 'unclassified',
 '8': 'cloud medium probability',
 '9': 'cloud high probability',
 '10': 'thin cirrus',
 '11': 'snow or ice'}

CPU times: user 20.9 ms, sys: 186 µs, total: 21 ms
Wall time: 20 ms


VBox()

In [38]:
# calculate NDVI
dsNDVI = calculate_indices(result, index='NDVI', satellite_mission='s2')
ndvi = dsNDVI["NDVI"]
display(ndvi)

<xarray.DataArray 'NDVI' (time: 6, y: 532, x: 830)>
dask.array<truediv, shape=(6, 532, 830), dtype=float32, chunksize=(1, 532, 830), chunktype=numpy.ndarray>
Coordinates:
  * time         (time) datetime64[ns] 2024-05-04T03:35:29.391000 ... 2024-05...
  * y            (y) float64 1.072e+06 1.072e+06 ... 1.067e+06 1.067e+06
  * x            (x) float64 5.95e+05 5.95e+05 5.95e+05 ... 6.033e+05 6.033e+05
    spatial_ref  int32 32648

In [39]:
%%time
# calculate average NDVI
average_ndvi = calculate_average(ndvi,time_pattern="1M")
progress(average_ndvi)

CPU times: user 13.2 ms, sys: 244 µs, total: 13.5 ms
Wall time: 12.6 ms


VBox()

In [40]:
# compute average_ndvi
average_ndvi = average_ndvi.compute()

In [41]:
fill_nan_model = joblib.load('model_train/regressor/500points/fill_nan_model_gb.pkl')

In [42]:
mask = ~np.isnan(average_ndvi)

In [43]:
cloud_free_points = np.stack([average_vh.values[~mask], average_vv.values[~mask]], axis=1)

In [44]:
# X_pred = np.stack([average_vh.values[~mask], average_vv.values[~mask]], axis=1)
average_ndvi.values[~mask] = fill_nan_model.predict(cloud_free_points)
average_ndvi_filled = xr.DataArray(average_ndvi, dims=average_ndvi.dims)

In [45]:
average_ndvi_filled.values

array([[[0.46482947, 0.46482947, 0.55715775, ..., 0.13884138,
         0.13884138, 0.23519422],
        [0.53762186, 0.53762186, 0.54759234, ..., 0.32184023,
         0.32184023, 0.50129557],
        [0.53762186, 0.53762186, 0.54759234, ..., 0.32184023,
         0.32184023, 0.50129557],
        ...,
        [0.31200743, 0.3240093 , 0.3548983 , ..., 0.65298665,
         0.6338502 , 0.6338502 ],
        [0.27736267, 0.26660758, 0.29234853, ..., 0.65298665,
         0.6338502 , 0.6338502 ],
        [0.17999999, 0.18418844, 0.21063744, ..., 0.65298665,
         0.6338502 , 0.6338502 ]]], dtype=float32)

###########################################################################################

In [46]:
print(average_ndvi.shape, average_vh.shape, average_vv.shape)

(1, 532, 830) (1, 532, 830) (1, 532, 830)


In [47]:
def extract_data_point(train, average_ndvi, dsvh, dsvv):
    loaded_datasets = {}
    for idx, point in train.iterrows():
        key = f"point_{idx + 1}"
        try:
            ndvi_data = average_ndvi.sel(x=point.geometry.x, y=point.geometry.y, method='nearest').values
            vh_data = dsvh.sel(x=point.geometry.x, y=point.geometry.y, method='nearest').values
            vv_data = dsvv.sel(x=point.geometry.x, y=point.geometry.y, method='nearest').values
            loaded_datasets[key] = {
                "data": np.stack((ndvi_data, vh_data, vv_data), axis=1),
                "label": point.Code
            }
        except Exception as e:
            # Handle the exception if necessary
            print(f"Error at point {key}: {e}")
    return loaded_datasets

In [48]:
def create_dataset(datasets):
    data_points = []
    labels = []
    for point_key, point_data in datasets.items():
        data_array = point_data['data']
        label = point_data['label']
        for row in data_array:
            data_points.append(row)
            labels.append(label)
    return data_points, labels

In [2]:
geo_path = "train/300point_data/ThuanHoa_DKS_300diem.shp"
# train_path = "train/updated_data/ThuanHoa_DKS_Kappa.shp"
points_label = load_data_geo(geo_path)
points_label

STT          LULC  Code                                geometry
0      1  Dat xay dung     8  POINT Z (601020.539 1068835.423 0.000)
1      2           CLN     5  POINT Z (600992.765 1068892.073 0.000)
2      3  Dat xay dung     8  POINT Z (600983.261 1068711.965 0.000)
3      4           Lua     3  POINT Z (600885.708 1069333.342 0.000)
4      5  Dat xay dung     8  POINT Z (600129.865 1069351.996 0.000)
5      6           CLN     5  POINT Z (600810.711 1068891.221 0.000)
6      7           CLN     5  POINT Z (600786.149 1069268.608 0.000)
7      8           Lua     3  POINT Z (600604.436 1069084.169 0.000)
8      9           CLN     5  POINT Z (600517.093 1069186.396 0.000)
9     10           CLN     5  POINT Z (600990.227 1068837.253 0.000)
10    11           CLN     5  POINT Z (599282.478 1070496.075 0.000)
11    12  Dat xay dung     8  POINT Z (599721.626 1070386.669 0.000)
12    13           CLN     5  POINT Z (599721.331 1070497.244 0.000)
13    14  Dat xay dung     8  POINT Z (599427.280 1070700.705 0.000)
14    15           CLN     5  POINT Z (601286.699 1069237.269 0.000)
15    16  Dat xay dung     8  POINT Z (600631.423 1069908.552 0.000)
16    17  Dat xay dung     8  POINT Z (600668.841 1069845.678 0.000)
17    18  Dat xay dung     8  POINT Z (600652.652 1069872.376 0.000)
18    19  Dat xay dung     8  POINT Z (600788.301 1069691.866 0.000)
19    20  Dat xay dung     8  POINT Z (600812.585 1069646.382 0.000)
20    21  Dat xay dung     8  POINT Z (600955.477 1069563.949 0.000)
21    22  Dat xay dung     8  POINT Z (600795.423 1069851.863 0.000)
22    23           Lua     3  POINT Z (601304.153 1069807.958 0.000)
23    24  Dat xay dung     8  POINT Z (601290.352 1069723.532 0.000)
24    25  Dat xay dung     8  POINT Z (601257.677 1069271.973 0.000)
25    26           CLN     5  POINT Z (601480.347 1069175.068 0.000)
26    27           CLN     5  POINT Z (601482.341 1069302.212 0.000)
27    28           Lua     3  POINT Z (601359.537 1069159.054 0.000)
28    29  Dat xay dung     8  POINT Z (601208.361 1069604.199 0.000)
29    30           Lua     3  POINT Z (601363.413 1069786.852 0.000)
30    31           CLN     5  POINT Z (601215.261 1069717.444 0.000)
31    32           Lua     3  POINT Z (601262.345 1069600.140 0.000)
32    33           CLN     5  POINT Z (601208.768 1069064.515 0.000)
33    34           CLN     5  POINT Z (600942.755 1069583.615 0.000)
34    35           Lua     3  POINT Z (600612.709 1068275.908 0.000)
35    36  Dat xay dung     8  POINT Z (600758.457 1068101.438 0.000)
36    37           Lua     3  POINT Z (600709.347 1070278.742 0.000)
37    38           CLN     5  POINT Z (602160.592 1070418.222 0.000)
38    39           CLN     5  POINT Z (600373.088 1070532.776 0.000)
39    40           CLN     5  POINT Z (600373.088 1070481.993 0.000)
40    41  Dat xay dung     8  POINT Z (600954.210 1070655.386 0.000)
41    42           Lua     3  POINT Z (602302.656 1070522.538 0.000)
42    43  Dat xay dung     8  POINT Z (602765.221 1070626.623 0.000)
43    44  Dat xay dung     8  POINT Z (602584.392 1070648.240 0.000)
44    45           CLN     5  POINT Z (600499.360 1070387.289 0.000)
45    46           Lua     3  POINT Z (600975.168 1070637.051 0.000)
46    47  Dat xay dung     8  POINT Z (602228.377 1070440.952 0.000)
47    48           Lua     3  POINT Z (602012.440 1070141.604 0.000)
48    49  Dat xay dung     8  POINT Z (601309.696 1069155.916 0.000)
49    50  Dat xay dung     8  POINT Z (600852.900 1069777.032 0.000)
50    51           CLN     5  POINT Z (601162.292 1069273.597 0.000)
51    52           Lua     3  POINT Z (601166.177 1069040.213 0.000)
52    53           Lua     3  POINT Z (600548.192 1067389.162 0.000)
53    54           Lua     3  POINT Z (601440.136 1068785.794 0.000)
54    55           Lua     3  POINT Z (600301.172 1069563.339 0.000)
55    56  Dat xay dung     8  POINT Z (600724.221 1069780.850 0.000)
56    57  Dat xay dung     8  POINT Z (600548.610 1070200.780 0.000)
57 

In [50]:
data_points = extract_data_point(points_label, average_ndvi_filled, average_vh, average_vv)
X_train, y_train = create_dataset(data_points)

In [72]:
loaded_model = joblib.load(os.path.join("model_train/new_classify", "classify_knn.joblib"))

In [73]:
%time
# dự đoán
y_pred = loaded_model.predict(X_train)


CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 13.8 µs


In [74]:
acc = accuracy_score(y_pred, y_train)
acc

0.2842809364548495

In [71]:
y_pred

array([5, 8, 5, 3, 8, 5, 3, 5, 3, 5, 3, 3, 5, 3, 5, 8, 5, 8, 5, 8, 9, 8,
       3, 9, 8, 5, 5, 9, 5, 5, 5, 9, 8, 9, 3, 8, 3, 5, 5, 5, 5, 3, 3, 3,
       8, 5, 8, 5, 9, 8, 3, 5, 5, 9, 5, 5, 8, 3, 5, 5, 9, 3, 5, 9, 9, 3,
       3, 8, 5, 3, 5, 9, 5, 5, 3, 3, 5, 5, 3, 3, 5, 9, 9, 3, 5, 5, 5, 5,
       5, 3, 3, 5, 3, 3, 3, 3, 3, 5, 5, 9, 3, 5, 3, 9, 5, 9, 5, 9, 5, 5,
       5, 5, 3, 9, 9, 3, 3, 3, 5, 5, 5, 5, 9, 9, 5, 8, 5, 9, 3, 3, 5, 3,
       5, 3, 3, 5, 3, 3, 3, 5, 5, 3, 3, 3, 5, 5, 5, 5, 5, 5, 9, 9, 5, 5,
       9, 5, 5, 5, 5, 5, 3, 8, 9, 5, 3, 3, 3, 8, 5, 3, 3, 3, 8, 3, 5, 3,
       3, 3, 3, 3, 3, 3, 5, 3, 5, 3, 5, 5, 5, 5, 3, 3, 5, 3, 3, 9, 3, 3,
       5, 5, 5, 5, 6, 9, 9, 5, 9, 5, 9, 8, 5, 9, 3, 9, 8, 9, 9, 9, 5, 5,
       5, 9, 9, 9, 5, 5, 3, 8, 3, 5, 5, 5, 8, 5, 5, 8, 5, 5, 8, 3, 5, 8,
       5, 5, 3, 8, 5, 5, 3, 8, 5, 8, 9, 5, 3, 3, 5, 5, 3, 9, 9, 8, 9, 5,
       5, 5, 3, 5, 3, 3, 8, 3, 5, 5, 9, 5, 3, 3, 5, 8, 5, 5, 5, 5, 5, 9,
       5, 5, 3, 5, 5, 5, 9, 3, 3, 3, 5, 3, 3])

In [ ]:
y_train